export enum DB_CONNECTION {
  CORP_REG_DB = 'MONGO_CORP_REG',
  MKT_DB = 'MONGO_MKT',
  MKT_DB_PROD = 'MONGO_MKT_PROD',
}

export enum ENV_VARS {
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
  GOOGLE_API_CLIENT_ID = 'GOOGLE_API_CLIENT_ID',
  GOOGLE_API_CLIENT_KEY = 'GOOGLE_API_CLIENT_KEY',
  GOOGLE_API_CLIENT_SECRET = 'GOOGLE_API_CLIENT_SECRET',
}
